### ISSUE TITLE
Flatpak Release Video

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#1892]
Flatpak 1.0 is getting released soon and the intention is to support the marketing efforts with a release video.

**Manuscript Draft**
> Flatpak is a sandboxing technology for the Linux desktop. It unifies application delivery and guarantees that your app runs consistently in deployment. The underlying core uses OSTree and innovative Linux kernel features to isolate and secure your apps. With Flatpak your app runs everywhere.
> 
> Hundreds of Flatpak'd apps are already delivered to Linux through the Flathub store.
> And since Flatpak is a decentralized technology, you can host your own flatpak store too.
> 
> The next generation of app delivery for Linux is already on its way. Learn how to flatpak your app today on flatpak.org.

**Voice-over**
@ssssam has volunteered to voice the video

**Music**
@TheBaronHimself has volunteered to compose a bit of music.

**Visuals**
@bastianilso has volunteered to create motion graphics for the video.

**Milestones**
- [x] Write a manuscript draft
- [x] Record voice-over
- [x] Collect visual assets
- [x] Find or compose music 
- [x] Draft storyboards for animations
- [x] Create & render animations 
- [x] Video Editing

**Comment by matthiasclasen** [comment]
Wow, that is pretty awesome as a start. Thanks for diving into this!

**Comment by aiamuzz** [comment]
great !!!

**Comment by bastianilso** [comment]
@jimmac suggested I used a less technical wording in the manuscript, so I rewrote it. I will record both versions with @ssssam .

**Manuscript Draft v2**

> Deploying apps to Linux is difficult because so many different Linux distributions exist.
> Crash reports pile up from angry users and that you cant reproduce.
> With Flatpak you can.
> Flatpak is an innovate technology which simplifies how your app can reach your users.
> It puts you in control of app upgrades.
> And ensures that your app runs equally excellent on all Linux platforms.
> Check out the hundreds of other apps on Flathub
> and Flatpak your app today.

**Comment by AsciiWolf** [comment]
> Deploying apps to Linux is difficult

"can be difficult" sounds better.

> Crash reports pile up from angry users

"unhappy users" sounds better. (Also, small typo: cant -> can't)

Anyway, great job!

**Comment by ssssam** [comment]
Version 3!

> Deploying apps to Linux can be difficult because there are so many different Linux distributions.
> Life isn't easy when crash reports pile up from angry users and you can't reproduce them yourself.
> But with Flatpak, you can.
> Flatpak uses container technology so that your app runs same way on all Linux-based platforms.
> It makes it simple to deliver your apps, so you can spend your time on more important things.
> And it puts you in control of updates so yours users can always get the newest version.
> Check out the hundreds of apps that are already available on Flathub
> and Flatpak your app today.

**Comment by bastianilso** [comment]
We recorded version 3. @brittyazel is editing and mastering the voice-over.

**Comment by brittyazel** [comment]
```
Life isn't easy when crash reports pile up from angry users and you can't reproduce them yourself.
But with Flatpak, you can.
```

It's hard when you can't reproduce the bugs reported by your users. But with Flatpak, you can!

**Comment by TheBaronHimself** [comment]
I can probably take care of the music.

**Comment by bastianilso** [comment]
Excellent, thank you @TheBaronHimself ! I have sent you the voice over and some inspiration. I will begin collecting visual assets needed to assemble the flatpak release video now.

**Comment by bastianilso** [comment]
I'm going to postpone my animation efforts two weeks more. I'm moving out of my apartment to a new town so schedule is a bit tight at the moment..

**Comment by TheBaronHimself** [comment]
Works for me :).

**Comment by bastianilso** [comment]
**Update:**  I have fleshed out a storyboard for the video and have most of the visual assets in place. Next step is to start animation which I imagine is a job I'll take on soon.

**Comment by bastianilso** [comment]
**Update:** I have begun the animation process.

9 Animations Total:
- [x]  Flying across the many distributions.
- [x]  Bugs everywhere.
- [x]  With Flatpak, you can.
- [ ]  Flatpak uses container technology.
- [ ]  Flatpaks rain from the sky.
- [ ]  The developers in heaven.
- [ ]  Much love.
- [ ]  Check out flathub.
- [ ]  Flatpak your app today.

**Comment by matthiasclasen** [comment]
yay!

**Comment by bastianilso** [comment]
The animation process has finished. @TheBaronHimself  I have sent you PMs with links to the current state of the video. If you need anything else to work on the music, let me know!

**Comment by bastianilso** [comment]
Me and @TheBaronHimself will be working on the last bit on Wednesday the 8th August and aim to have it finished by next week.

**Comment by alexlarsson** [comment]
@bastianilso Sweet! The plan is to release some time next week.

**Comment by allanday** [comment]
Someone showed me the video a little while ago - it looks really good!

The video seems to be more of a general introduction to Flatpak, rather than a video about the 1.0 release specifically. As such, we might want to use it for general marketing. What about hosting it on the [about page](https://flatpak.org/about/)?

We can still link to it from the press release.

**Comment by bastianilso** [comment]
@allanday Excellent idea and I agree. I think it makes it a more re-usable too, this way.

@TheBaronHimself sent me the music today and I am preparing a final render. Note that the 3D scenes have changed based on feedback from @jimmac.

Do we have a youtube channel for Flatpak or is there an intention to make one?

**Comment by aiamuzz** [comment]
am excited as well ... in fact i did try to work on a story board ... but wasn't able to in time ... anyway i can get a sneak at the preview ? ... i promise a NDA(being from the creative field i understand that would be in order) ... :)

**Comment by TheBaronHimself** [comment]
Just had a quick chat with @bastianilso. We're looking to finish the video until Tuesday or Wednesday.

**Comment by allanday** [comment]
Can I view the video anywhere? I'm trying to figure out how to integrate it into the website.

**Comment by bastianilso** [comment]
@allanday video is not online yet except on hidden youtube draft links on my channel.

When the video finishes I will attach it to this thread. 
I suggest we also get a YouTube channel for Flatpak too. What do you think?

**Comment by allanday** [comment]
> @allanday video is not online yet except on hidden youtube draft links on my channel.

I'm in the middle of preparing website updates to accommodate the video. Knowing what's in the video would be helpful. Is there no way you can share the draft with me?

> I suggest we also get a YouTube channel for Flatpak too. What do you think?

It's the obvious solution for hosting the video... I don't know if there are alternatives to consider.

If you do create an account, do use an @gnome.org email alias, so it's not tied to a specific individual!

**Comment by allanday** [comment]
> Can I view the video anywhere? I'm trying to figure out how to integrate it into the website.

Never mind, someone shared it with me.

**Comment by bastianilso** [comment]
@allanday apologize, I thought you meant you wanted the final version which is not online yet. anyway, I hope you worked it out, otherwise the manuscript can be read in this issue and a final version will be available tomorrow.

I will create a flatpak channel for video@gnome.org then.

**Comment by bastianilso** [comment]
**Update:** The video is almost ready and I expect to upload it later this afternoon. 

Flatpak has a YouTube channel now:
https://www.youtube.com/channel/UC5qrehIqUYquF-bDOV8JSrA

@allanday You can sign in to the channel with our video@gnome.org account and then go to "Switch Accounts". There is an unlisted draft version uploaded, but I will reupload a final public version.

**Comment by bastianilso** [comment]
The video has now finished and resides as unlisted inside Flatpak's youtube channel.
Should we release it now as public or change its publicity in coordination with the Flatpak 1.0 release?

**Comment by aiamuzz** [comment]
@alexlarsson ... and team ...
You need to list the complete functional feature set and if possible the future milestone(or the general direction you intend to take Flatpak to going forward) ... and all this needs to be part of the the video ... only then will this attain the official launch status.

@bastianilso  ...  without the above details ... or releasing it before the release of version 1.0 ... will make this video a Flatpak fan video rather than an official launch video.

**Comment by matthiasclasen** [comment]
Thats up to the flatpak team to decide

**Comment by allanday** [comment]
>  Should we release it now as public or change its publicity in coordination with the Flatpak 1.0 release?

We need it publishing now. I've looked on the Flatpak Youtube channel, but I can't see the unlisted video.

**Comment by bastianilso** [comment]
@allanday it is only visible if you go to "Creator Studio" (for some reason Youtube hides unlisted/private videos in the channels). Anyway, I have taken the liberty to change its visibility to "Public" now. Here is a link:

https://youtu.be/jDVCITRWGgs

**Comment by alexlarsson** [comment]
All done
